name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t spidybhai/mleech
    - name: login
      run: docker login -u spidybhai -p DockerHub@69 && docker push spidybhai/mleech
